# render.yaml
services:
  - type: web
    name: kognia_backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.11.9